version: "3.7"

services:
    server:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: server
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - database

    database:
        image: mysql:latest
        container_name: database
        ports:
            - "8899:3306"
        volumes:
            - ./tmp/database:/var/lib/mysql
        environment:
             MYSQL_ROOT_PASSWORD: root
             MYSQL_DATABASE: footberg_db
             MYSQL_USER: footberg
             MYSQL_PASSWORD: footberg
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

    nginx:
        image: nginx:stable
        container_name: nginx
        restart: no
        links:
            - server
        ports:
            - "10021:80"
        volumes:
            - ./:/var/www
            - ./docker/conf.d/nginx.conf:/etc/nginx/conf.d/default.conf

